version: '3'
services:
  app:
    container_name: url-shortner-service
    restart: always
    build: .
    ports:
      - '5000:5000'
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'