POST http://localhost:5000/api/url/shorten
Content-Type: application/json

{
    "longUrl": "https://www.google.com/search?q=python&rlz=1C5CHFA_enCA911CA911&sxsrf=AOaemvKbzcbPO7Voa7q6Zajbew8kYvBP3A%3A1630678974638&ei=vi8yYYayJsi6tAbxoYvYCw&oq=python&gs_lcp=Cgdnd3Mtd2l6EAMyBAgjECcyBQgAEJECMgcIABCxAxBDMgUIABCRAjIHCAAQsQMQQzIECAAQQzIICAAQgAQQsQMyCAgAEIAEELEDMggIABCABBCxAzIFCAAQgAQ6BwgjELADECc6BwgAEEcQsAM6BwgAELADEEM6DQguELEDEMcBENEDEEM6DgguEIAEELEDEMcBEKMCOgsILhCABBDHARDRAzoNCC4QsQMQxwEQowIQQzoKCC4QxwEQrwEQQzoICC4QsQMQgwE6CwguELEDEJECEJMCOg4ILhCABBCxAxDHARDRAzoRCC4QgAQQsQMQgwEQxwEQ0QM6CwgAEIAEELEDEIMBOgsIABCABBCxAxDJAzoFCAAQkgM6BAguEEM6CwguEMcBEK8BEJECOgsILhDHARDRAxCRAjoFCC4QgAQ6EQguEIAEELEDEIMBEMcBEKMCSgUIPBIBMUoECEEYAVDxIlirUmCgVGgBcAB4AIABiwGIAe0HkgEDNS41mAEAoAEByAEKwAEB&sclient=gws-wiz&ved=0ahUKEwiGiZrIgOPyAhVIHc0KHfHQArsQ4dUDCA4&uact=5"
}