POST http://localhost:4000/api/url/shorten
Content-Type: application/json

{
    "longUrl": "https://www.google.com/search?q=canada&sxsrf=AOaemvITJmtN6SLjtZCCGcnqB0oF6DPG4w:1631045331176&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjOzM6s1e3yAhWOct8KHf0RAFQQ_AUoA3oECAEQBQ&biw=1440&bih=789"
}